export const MOTOR_VEHICLE_TYPES_LIST = 'MOTOR_VEHICLE_TYPES_LIST';
export const MOTOR_VEHICLE_TYPES_SUCCESS = 'MOTOR_VEHICLE_TYPES_SUCCESS';
export const MOTOR_VEHICLE_TYPES_FAILURE = 'MOTOR_VEHICLE_TYPES_FAILURE';
export const ADDING_MOTOR_VEHICLE_TYPE = 'ADDING_MOTOR_VEHICLE_TYPE';
export const ADDING_MOTOR_VEHICLE_TYPE_SUCCESS = 'ADDING_MOTOR_VEHICLE_TYPE_SUCCESS';
export const ADDING_MOTOR_VEHICLE_TYPE_FAILURE = 'ADDING_MOTOR_VEHICLE_TYPE_FAILURE';
