export const CLIENTS_RESET = "CLIENTS_RESET";
export const GET_CLIENTS_START = "GET_CLIENTS_START";
export const GET_CLIENTS_SUCCESS = "GET_CLIENTS_SUCCESS";
export const GET_CLIENTS_FAILED = "GET_CLIENTS_FAILED";
export const ADD_CLIENT_SUCCESS = "ADD_CLIENT_SUCCESS";
export const ADD_CLIENT_FAILED = "ADD_CLIENT_FAILED";
export const GET_SINGLE_CLIENT_SUCCESS = "GET_SINGLE_CLIENT_SUCCESS";
export const GET_SINGLE_CLIENT_FAILED = "GET_SINGLE_CLIENT_FAILED";