export const FETCHING_INSUARANCE_COVERS_LIST = 'FETCHING_INSUARANCE_COVERS_LIST';
export const FETCHING_INSUARANCE_COVERS_SUCCESS = 'FETCHING_INSUARANCE_COVERS_SUCCESS';
export const FETCHING_INSUARANCE_COVERS_FAILURE = 'FETCHING_INSUARANCE_COVERS_FAILURE';
export const ADDING_INSUARANCE_COVER = 'ADDING_INSUARANCE_COVER';
export const ADDING_INSUARANCE_COVER_SUCCESS = 'ADDING_INSUARANCE_COVER_SUCCESS';
export const ADDING_INSUARANCE_COVER_FAILURE = 'ADDING_INSUARANCE_COVER_FAILURE';
