export const FETCH_OPTIONS = 'FETCH_OPTIONS';
export const FETCH_OPTIONS_SUCCESS = 'FETCH_OPTIONS_SUCCESS';
export const FETCH_OPTIONS_FAILURE = 'FETCH_OPTIONS_FAILURE';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const ADD_TRANSACTION_SUCCESS = 'ADD_TRANSACTION_SUCCESS';
export const ADD_TRANSACTION_FAILURE = 'ADD_TRANSACTION_FAILURE';
export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';
export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS';
export const FETCH_TRANSACTIONS_FAILURE = 'FETCH_TRANSACTIONS_FAILURE';
export const FETCH_TRANSACTIONS_BY_ID = 'FETCH_TRANSACTIONS_BY_ID';
export const FETCH_TRANSACTIONS_BY_ID_SUCCESS = 'FETCH_TRANSACTIONS_BY_ID_SUCCESS';
export const FETCH_TRANSACTIONS_BY_ID_FAILURE = 'FETCH_TRANSACTIONS_BY_ID_FAILURE';
// client options
export const FETCH_CLIENT_OPTIONS = 'FETCH_CLIENT_OPTIONS';
export const FETCH_CLIENT_OPTIONS_SUCCESS = 'FETCH_CLIENT_OPTIONS_SUCCESS';
export const FETCH_CLIENT_OPTIONS_FAILURE = 'FETCH_CLIENT_OPTIONS_FAILURE';

// insuarance class options
export const FETCH_INSURANCE_CLASS_OPTIONS = 'FETCH_INSURANCE_CLASS_OPTIONS';
export const FETCH_INSURANCE_CLASS_OPTIONS_SUCCESS = 'FETCH_INSURANCE_CLASS_OPTIONS_SUCCESS';
export const FETCH_INSURANCE_CLASS_OPTIONS_FAILURE = 'FETCH_INSURANCE_CLASS_OPTIONS_FAILURE';

// insuarance cover options
export const FETCH_INSURANCE_COVER_OPTIONS = 'FETCH_INSURANCE_COVER_OPTIONS';
export const FETCH_INSURANCE_COVER_OPTIONS_SUCCESS = 'FETCH_INSURANCE_COVER_OPTIONS_SUCCESS';
export const FETCH_INSURANCE_COVER_OPTIONS_FAILURE = 'FETCH_INSURANCE_COVER_OPTIONS_FAILURE';

// motor vehicle type options
export const FETCH_MOTOR_VEHICLE_TYPE_OPTIONS = 'FETCH_MOTOR_VEHICLE_TYPE_OPTIONS';
export const FETCH_MOTOR_VEHICLE_TYPE_OPTIONS_SUCCESS = 'FETCH_MOTOR_VEHICLE_TYPE_OPTIONS_SUCCESS';
export const FETCH_MOTOR_VEHICLE_TYPE_OPTIONS_FAILURE = 'FETCH_MOTOR_VEHICLE_TYPE_OPTIONS_FAILURE';

// motor vehicle model options
export const FETCH_MOTOR_VEHICLE_MODEL_OPTIONS = 'FETCH_MOTOR_VEHICLE_MODEL_OPTIONS';
export const FETCH_MOTOR_VEHICLE_MODEL_OPTIONS_SUCCESS = 'FETCH_MOTOR_VEHICLE_MODEL_OPTIONS_SUCCESS';
export const FETCH_MOTOR_VEHICLE_MODEL_OPTIONS_FAILURE = 'FETCH_MOTOR_VEHICLE_MODEL_OPTIONS_FAILURE';
