export const IS_LOGIN_SUCCESSFUL = "IS_LOGIN_SUCCESSFUL";
export const IS_LOGIN_FAILED = "IS_LOGIN_FAILED";
export const IS_REGISTER_SUCCESSFUL = "IS_REGISTER_SUCCESSFUL";
export const IS_REGISTER_FAILED = "IS_REGISTER_FAILED";
export const LOG_OUT = "LOG_OUT";