export const MOTOR_VEHICLE_MODELS_LIST = 'MOTOR_VEHICLE_MODELS_LIST';
export const MOTOR_VEHICLE_MODELS_SUCCESS = 'MOTOR_VEHICLE_MODELS_SUCCESS';
export const MOTOR_VEHICLE_MODELS_FAILURE = 'MOTOR_VEHICLE_MODELS_FAILURE';
export const ADDING_MOTOR_VEHICLE_MODEL = 'ADDING_MOTOR_VEHICLE_MODEL';
export const ADDING_MOTOR_VEHICLE_MODEL_SUCCESS = 'ADDING_MOTOR_VEHICLE_MODEL_SUCCESS';
export const ADDING_MOTOR_VEHICLE_MODEL_FAILURE = 'ADDING_MOTOR_VEHICLE_MODEL_FAILURE';