export const FETCHING_INSUARANCE_CLASSES_LIST = 'FETCHING_INSUARANCE_CLASSES_LIST';
export const FETCHING_INSUARANCE_CLASSES_SUCCESS = 'FETCHING_INSUARANCE_CLASSES_SUCCESS';
export const FETCHING_INSUARANCE_CLASSES_FAILURE = 'FETCHING_INSUARANCE_CLASSES_FAILURE';
export const ADDING_INSUARANCE_CLASS = 'ADDING_INSUARANCE_CLASS';
export const ADDING_INSUARANCE_CLASS_SUCCESS = 'ADDING_INSUARANCE_CLASS_SUCCESS';
export const ADDING_INSUARANCE_CLASS_FAILURE = 'ADDING_INSUARANCE_CLASS_FAILURE';
